select_local: c
select_incoming: r
toggle_view: v
show_up: S
show_down: T 
scroll_up: t
scroll_down: s
edit: e
next: n
previous: p
quit: q
help: h

# Set to `true` to skip having to press enter when entering commands
cont_eval: true
